--Inserções para o banco 4ban

INSERT INTO Tag (tag_nome, tag_descricao) VALUES('geral', 'Assuntos gerais, sem um tópico especifico');
INSERT INTO Tag (tag_nome, tag_descricao) VALUES('ti', 'Assuntos relacionados à tecnologia da Informação');
INSERT INTO Tag (tag_nome, tag_descricao) VALUES('noticia', 'Noticias ou acontecimentos recentes.');
INSERT INTO Tag (tag_nome, tag_descricao) VALUES('gastronomia', 'Culinária em geral');
INSERT INTO Tag (tag_nome, tag_descricao) VALUES('interessante', 'auto explicativo');
INSERT INTO Tag (tag_nome, tag_descricao) VALUES('estranho', 'auto explicativo');



INSERT INTO Usuario(usuario_email, usuario_login, usuario_senha, usuario_username, usuario_adm, usuario_data_cadastro) VALUES('lenticar@gmail.com', 'lenticar', 'lenticar', 'lenticar', true, '2020-01-01');
INSERT INTO Usuario(usuario_email, usuario_login, usuario_senha, usuario_username, usuario_adm, usuario_data_cadastro) VALUES('arthider@gmail.com', 'arthider', 'arthider', 'arthider', false, '2020-02-01');
INSERT INTO Usuario(usuario_email, usuario_login, usuario_senha, usuario_username, usuario_adm, usuario_data_cadastro) VALUES('rchmahet@gmail.com', 'rchmahet', 'rchmahet', 'rchmahet', false, '2020-03-01');
INSERT INTO Usuario(usuario_email, usuario_login, usuario_senha, usuario_username, usuario_adm, usuario_data_cadastro) VALUES('tershbul@gmail.com', 'tershbul', 'tershbul', 'tershbul', false, '2020-04-01');
INSERT INTO Usuario(usuario_email, usuario_login, usuario_senha, usuario_username, usuario_adm, usuario_data_cadastro) VALUES('iblescup@gmail.com', 'iblescup', 'iblescup', 'iblescup', false, '2020-05-01');




INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('torquent per conubia nostra, per inceptos hymenaeos.',194,192,'2020-01-13','ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Maecenas libero est, congue a, aliquet vel,',238,251,'2020-01-13','lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Cum sociis natoque penatibus et magnis dis',45,337,'2020-01-13','sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('aliquet odio. Etiam ligula tortor, dictum eu,',235,266,'2020-01-13','ipsum. Phasellus',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Integer tincidunt aliquam arcu. Aliquam ultrices iaculis',311,180,'2020-01-13','conubia nostra, per inceptos',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Aliquam ornare, libero at auctor ullamcorper, nisl',228,227,'2020-01-13','turpis. Nulla aliquet. Proin velit. Sed malesuada',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('est arcu ac orci. Ut semper pretium',99,9,'2020-01-13','sed consequat',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('neque vitae semper egestas, urna justo faucibus',174,371,'2020-01-13','vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('ut, nulla. Cras eu tellus eu augue',291,451,'2020-01-13','Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('lorem eu metus. In lorem. Donec elementum,',338,117,'2020-01-13','Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('turpis vitae purus gravida sagittis. Duis gravida.',111,143,'2020-01-13','Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('interdum feugiat. Sed nec metus facilisis lorem',93,200,'2020-01-13','sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('risus. Donec nibh enim, gravida sit amet,',1,34,'2020-01-13','mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('molestie tortor nibh sit amet orci. Ut',461,308,'2020-01-13','tempor, est ac mattis semper, dui',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Nullam feugiat placerat velit. Quisque varius. Nam',30,73,'2020-01-13','eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non,',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('eleifend nec, malesuada ut, sem. Nulla interdum.',47,402,'2020-01-13','eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('luctus sit amet, faucibus ut, nulla. Cras',218,195,'2020-01-13','convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('arcu ac orci. Ut semper pretium neque.',486,142,'2020-01-13','nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum,',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('lacus. Cras interdum. Nunc sollicitudin commodo ipsum.',305,137,'2020-01-13','pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('nec, imperdiet nec, leo. Morbi neque tellus,',71,358,'2020-01-13','pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('auctor, nunc nulla vulputate dui, nec tempus',390,417,'2020-01-13','sapien imperdiet ornare. In faucibus. Morbi vehicula.',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('diam vel arcu. Curabitur ut odio vel',30,52,'2020-01-13','ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Nullam ut nisi a odio semper cursus.',357,67,'2020-01-13','mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('aliquam, enim nec tempus scelerisque, lorem ipsum',355,249,'2020-01-13','vulputate ullamcorper magna. Sed eu eros. Nam',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('et, lacinia vitae, sodales at, velit. Pellentesque',217,242,'2020-01-13','nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Sed pharetra, felis eget varius ultrices, mauris',177,451,'2020-01-13','sit amet metus. Aliquam erat volutpat. Nulla facilisis.',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('sit amet ultricies sem magna nec quam.',483,13,'2020-01-13','tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('libero. Integer in magna. Phasellus dolor elit,',140,67,'2020-01-13','malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis,',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('mattis ornare, lectus ante dictum mi, ac',370,83,'2020-01-13','In at pede. Cras vulputate velit eu sem.',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('nibh. Aliquam ornare, libero at auctor ullamcorper,',197,285,'2020-01-13','neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('tristique neque venenatis lacus. Etiam bibendum fermentum',256,64,'2020-01-13','nisl elementum purus,',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('dolor vitae dolor. Donec fringilla. Donec feugiat',468,240,'2020-01-13','Duis',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('quis diam luctus lobortis. Class aptent taciti',447,190,'2020-01-13','ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('urna. Vivamus molestie dapibus ligula. Aliquam erat',227,177,'2020-01-13','in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('viverra. Maecenas iaculis aliquet diam. Sed diam',346,107,'2020-01-13','eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('augue scelerisque mollis. Phasellus libero mauris, aliquam',458,339,'2020-01-13','taciti sociosqu ad litora',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('elit, pellentesque a, facilisis non, bibendum sed,',239,317,'2020-01-13','ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('urna suscipit nonummy. Fusce fermentum fermentum arcu.',231,355,'2020-01-13','Cras vulputate',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('sit amet risus. Donec egestas. Aliquam nec',323,96,'2020-01-13','Pellentesque habitant morbi tristique senectus et netus et malesuada',3);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('tellus lorem eu metus. In lorem. Donec',432,373,'2020-01-13','aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('nulla. Integer urna. Vivamus molestie dapibus ligula.',319,50,'2020-01-13','elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('taciti sociosqu ad litora torquent per conubia',252,119,'2020-01-13','montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('ipsum. Phasellus vitae mauris sit amet lorem',54,454,'2020-01-13','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',4);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('sociis natoque penatibus et magnis dis parturient',121,133,'2020-01-13','vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('consectetuer euismod est arcu ac orci. Ut',276,302,'2020-01-13','interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('arcu. Vestibulum ante ipsum primis in faucibus',230,8,'2020-01-13','Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('vulputate mauris sagittis placerat. Cras dictum ultricies',138,391,'2020-01-13','non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit',2);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('vitae, orci. Phasellus dapibus quam quis diam.',433,275,'2020-01-13','sem, consequat nec, mollis vitae, posuere',5);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('Sed dictum. Proin eget odio. Aliquam vulputate',397,330,'2020-01-13','imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque',1);
INSERT INTO Postagem (postagem_titulo,postagem_up,postagem_down,postagem_data_publicacao,postagem_texto,fk_usuario_id) VALUES ('auctor odio a purus. Duis elementum, dui',306,471,'2020-01-13','non justo. Proin non massa non',5);


INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','sed consequat auctor, nunc',1,null,22,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','commodo at, libero. Morbi accumsan laoreet ipsum.',0,null,43,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','quis urna. Nunc quis arcu vel quam dignissim pharetra.',0,null,18,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Cras dolor dolor, tempus non, lacinia at, iaculis quis,',0,null,37,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ridiculus mus. Proin vel nisl. Quisque fringilla',1,null,45,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','cursus',1,null,7,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','tristique senectus',1,null,3,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla',0,null,30,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis',1,null,13,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','arcu vel quam dignissim pharetra. Nam ac nulla.',0,null,2,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Pellentesque ut ipsum ac mi eleifend egestas.',1,null,49,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Vivamus nisi.',1,null,9,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','sollicitudin a, malesuada id,',0,null,30,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','malesuada ut, sem. Nulla',1,null,34,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Mauris nulla. Integer urna. Vivamus molestie dapibus',1,null,5,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','viverra. Maecenas iaculis aliquet',1,null,16,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','dictum eleifend, nunc risus varius orci,',1,null,17,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Curabitur ut',1,null,18,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Cras convallis convallis dolor. Quisque',0,null,32,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','erat semper rutrum.',1,null,2,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','dolor vitae dolor. Donec fringilla. Donec',0,null,48,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','neque sed sem',1,null,9,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ut, molestie in, tempus eu,',0,null,12,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod',0,null,31,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','amet metus. Aliquam erat volutpat.',1,null,4,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','risus, at fringilla purus mauris a',1,null,48,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','nisl. Quisque fringilla euismod enim.',1,null,50,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo',1,null,48,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Morbi non sapien',0,null,20,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum',1,null,19,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','velit. Cras lorem lorem, luctus ut, pellentesque',0,null,45,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','eros non enim commodo hendrerit. Donec porttitor tellus',1,null,27,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','molestie pharetra nibh. Aliquam ornare,',1,null,5,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','luctus lobortis. Class aptent taciti sociosqu ad',0,null,12,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','quam vel sapien imperdiet',0,null,49,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','semper egestas, urna justo faucibus lectus, a sollicitudin orci',1,null,2,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','quis accumsan convallis, ante lectus',0,null,48,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','neque vitae semper egestas, urna',0,null,31,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','dolor dapibus',0,null,37,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec',1,null,26,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','aliquet. Proin velit. Sed malesuada augue ut lacus.',0,null,15,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','mus.',1,null,46,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','aliquet, metus urna convallis erat, eget tincidunt dui augue',0,null,44,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','nibh. Phasellus nulla. Integer vulputate, risus',0,null,49,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','nulla. Cras eu tellus',0,null,17,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','amet nulla. Donec non justo.',1,null,14,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ornare lectus justo eu arcu.',1,null,17,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','elit pede, malesuada vel, venenatis vel, faucibus',0,null,6,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ut lacus. Nulla tincidunt, neque vitae semper',0,null,31,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','magna, malesuada vel, convallis in, cursus et, eros.',1,null,5,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus',0,null,19,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','dictum eu, placerat eget, venenatis a, magna.',0,null,20,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','nunc. Quisque ornare tortor at',0,null,17,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','elit, a feugiat tellus lorem',0,null,30,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','porttitor tellus non magna. Nam',0,null,26,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,',1,null,20,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','sed leo. Cras vehicula aliquet libero. Integer in magna.',1,null,10,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Suspendisse ac metus vitae velit',1,null,28,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ac',0,null,21,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','velit. Quisque varius. Nam porttitor scelerisque',1,null,33,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','est tempor bibendum. Donec felis orci, adipiscing non, luctus sit',1,null,30,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','justo eu arcu. Morbi',0,null,11,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','molestie arcu. Sed',0,null,31,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','amet',0,null,49,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','aliquam, enim nec tempus scelerisque, lorem ipsum',1,null,6,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','sed turpis nec mauris blandit',0,null,36,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend,',1,null,17,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','leo elementum sem, vitae aliquam eros turpis non enim. Mauris',1,null,32,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','consequat',1,null,45,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','non, lacinia at, iaculis quis, pede. Praesent',1,null,4,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum',1,null,48,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','enim nec',1,null,25,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','vel, faucibus',1,null,37,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','sit amet ornare lectus justo eu arcu.',1,null,22,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','et',0,null,29,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','mollis. Phasellus libero mauris, aliquam eu,',0,null,22,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','massa. Mauris vestibulum,',1,null,4,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','dapibus ligula.',1,null,42,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur',0,null,14,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam',1,null,2,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','consequat auctor, nunc nulla vulputate dui, nec',0,null,21,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Integer',1,null,26,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','tellus eu',1,null,22,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','odio. Phasellus at',1,null,13,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Aenean sed pede nec ante blandit',0,null,17,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate,',1,null,32,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','enim mi tempor lorem,',0,null,39,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','nec ligula consectetuer rhoncus.',1,null,7,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','in, cursus et, eros. Proin',0,null,35,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','sed orci lobortis augue scelerisque',1,null,12,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis.',0,null,42,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ornare, lectus',0,null,35,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','ut cursus luctus,',1,null,15,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','nonummy',1,null,40,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','urna justo faucibus lectus,',0,null,29,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum.',1,null,36,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','urna et',0,null,19,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Quisque imperdiet, erat nonummy ultricies ornare,',0,null,2,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','Aenean eget magna. Suspendisse tristique neque venenatis lacus.',1,null,36,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-03-09','dui nec urna',1,null,45,5);

--====================25 respostas de comentarios, limitadas aos primeiros 25 comentarios(distribuição aleatósria)====================

INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','et arcu imperdiet ullamcorper. Duis at lacus.',0,1,10,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','risus a ultricies adipiscing, enim mi tempor lorem, eget',1,13,26,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','at sem molestie',1,17,9,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','amet, risus.',0,23,20,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','aliquet, sem ut cursus luctus, ipsum',1,16,46,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','vulputate',0,12,9,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','erat. Etiam vestibulum massa rutrum magna. Cras convallis',1,12,38,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','neque. Morbi quis urna.',0,7,33,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','facilisis, magna tellus faucibus leo, in lobortis tellus',1,7,12,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','adipiscing ligula. Aenean gravida nunc sed pede. Cum',1,3,35,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','ligula.',1,18,41,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis',1,11,38,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in',1,12,19,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','Sed neque. Sed eget lacus. Mauris non',1,5,8,3);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','ante. Maecenas mi felis, adipiscing fringilla, porttitor',0,1,6,5);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','ligula. Aenean gravida nunc sed pede. Cum sociis',1,8,28,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','Integer in magna. Phasellus dolor elit, pellentesque',0,14,44,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','quam. Pellentesque habitant morbi tristique senectus',1,25,1,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','aliquet diam. Sed diam lorem, auctor quis, tristique',0,25,10,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','euismod ac, fermentum vel, mauris. Integer sem',0,20,17,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','diam eu dolor egestas rhoncus. Proin nisl',1,10,40,2);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','Nam ligula',1,17,47,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','pharetra, felis eget varius ultrices, mauris ipsum porta elit, a',0,15,12,1);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','Vivamus',1,21,39,4);
INSERT INTO Comentario (comentario_data_publicacao,comentario_texto,comentario_fixado,fk_comentario_id,fk_postagem_id,fk_usuario_id) VALUES ('2020-04-22','est tempor bibendum. Donec felis orci, adipiscing non, luctus sit',1,5,8,2);



INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (3,40);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,46);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (6,5);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (2,16);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (6,40);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (1,15);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (5,1);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (5,39);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (2,8);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,41);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (6,23);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (5,21);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (6,22);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (2,6);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (1,10);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (6,9);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (2,37);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (2,42);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,35);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (3,45);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (5,42);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (3,30);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (5,43);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,43);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (3,37);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (5,40);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,26);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (1,2);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (6,19);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (1,19);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,20);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (2,21);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (6,44);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,5);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (4,15);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (3,39);
INSERT INTO tag_has_postagem (fk_tag_id,fk_postagem_id) VALUES (1,46);
